name: Release

on:
  release:
    types: [ published ]

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    env:
      TERM: dumb
    steps:
      - uses: actions/checkout@v4
      - name: set up JDK 18
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 18
      - name: Decrypt secrets
        run: |
          echo ${{ secrets.ENCRYPT_KEY }} | release/signing-unpack.sh
      - name: Deploy to Sonatype
        run: |
          ./gradlew :publishAggregatedPublicationToCentralPortal --no-configuration-cache
      - name: Build AAB & APK
        run: |
          ./gradlew :demo:bundleRelease :demo:assembleRelease
      - name: Upload APK to release
        uses: softprops/action-gh-release@v2
        id: release
        with:
          files: |
            demo/build/outputs/apk/release/demo-release.apk
      - name: Clean secrets
        if: always()
        run: release/signing-cleanup.sh
